#!/usr/bin/env python
from misc.utility.scons_hints import *
from misc.utility.color import print_info


Import('env')
Import("env_modules")

module_env = env_modules.Clone()

if ARGUMENTS.get('ynet', 'no') == 'yes':
    module_env.Append(CPPDEFINES=["YNET"])

if ARGUMENTS.get('fmodgodot', 'yes') == 'no':
    module_env.Append(CPPDEFINES=["NO_FMOD"])
    print_info("Yarn Engine building with Dummy FMOD Objects")

if ARGUMENTS.get('ygodot', 'yes') == 'yes':
    module_env.Append(CPPDEFINES=["YGODOT"])
    print_info("Yarn Engine building with YGodot flag")

if env.editor_build:
    print_info("Yarn Engine Editor Build")
    module_env.add_source_files(env.modules_sources, "./editor/*.cpp")

module_env.add_source_files(env.modules_sources, "importers/*.cpp")
module_env.add_source_files(env.modules_sources, "*.cpp")

if ARGUMENTS.get('fmodgodot', 'yes') == 'no':
    module_env.add_source_files(env.modules_sources, "disabled_fmod/*.cpp")